In [2]:
import pandas
import csv
import pandas as pd

In [3]:
NB20 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2020_totals.html')
NB19 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2019_totals.html')
NB18 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2018_totals.html')
NB17 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2017_totals.html')
NB16 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2016_totals.html')
NB15 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')
NB15 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')
NB14 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2014_totals.html')
NB13 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2013_totals.html')
NB12 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2012_totals.html')
NB11 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2011_totals.html')
NB10 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2010_totals.html')
NB09 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2009_totals.html')
NB08 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2008_totals.html')
NB07 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2007_totals.html')
NB06 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2006_totals.html')
NB05 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2005_totals.html')
NB04 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2004_totals.html')
NB03 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2003_totals.html')
NB02 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2002_totals.html')
NB01 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2001_totals.html')
NB00 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_2000_totals.html')
NB99 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_1999_totals.html')
NB98 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_1998_totals.html')
NB97 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_1997_totals.html')
NB96 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_1996_totals.html')
NB95 = pandas.read_html('https://www.basketball-reference.com/leagues/NBA_1995_totals.html')

In [4]:
NB20 = NB20[0].dropna(axis=0, thresh=4)
NB19 = NB19[0].dropna(axis=0, thresh=4)
NB18 = NB18[0].dropna(axis=0, thresh=4)
NB17 = NB17[0].dropna(axis=0, thresh=4)
NB16 = NB16[0].dropna(axis=0, thresh=4)
NB15 = NB15[0].dropna(axis=0, thresh=4)
NB14 = NB14[0].dropna(axis=0, thresh=4)
NB13 = NB13[0].dropna(axis=0, thresh=4)
NB12 = NB12[0].dropna(axis=0, thresh=4)
NB11 = NB11[0].dropna(axis=0, thresh=4)
NB10 = NB10[0].dropna(axis=0, thresh=4)
NB09 = NB09[0].dropna(axis=0, thresh=4)
NB08 = NB08[0].dropna(axis=0, thresh=4)
NB07 = NB07[0].dropna(axis=0, thresh=4)
NB06 = NB06[0].dropna(axis=0, thresh=4)
NB05 = NB05[0].dropna(axis=0, thresh=4)
NB04 = NB04[0].dropna(axis=0, thresh=4)
NB03 = NB03[0].dropna(axis=0, thresh=4)
NB02 = NB02[0].dropna(axis=0, thresh=4)
NB01 = NB01[0].dropna(axis=0, thresh=4)
NB00 = NB00[0].dropna(axis=0, thresh=4)
NB99 = NB99[0].dropna(axis=0, thresh=4)
NB98 = NB98[0].dropna(axis=0, thresh=4)
NB97 = NB97[0].dropna(axis=0, thresh=4)
NB96 = NB96[0].dropna(axis=0, thresh=4)
NB95 = NB95[0].dropna(axis=0, thresh=4)

In [5]:
NB20['Season'] = 2020
NB19['Season'] = 2019
NB18['Season'] = 2018
NB17['Season'] = 2017
NB16['Season'] = 2016
NB15['Season'] = 2015
NB14['Season'] = 2014
NB13['Season'] = 2013
NB12['Season'] = 2012
NB11['Season'] = 2011
NB10['Season'] = 2010
NB09['Season'] = 2009
NB08['Season'] = 2008
NB07['Season'] = 2007
NB06['Season'] = 2006
NB05['Season'] = 2005
NB04['Season'] = 2004
NB03['Season'] = 2003
NB02['Season'] = 2002
NB01['Season'] = 2001
NB00['Season'] = 2000
NB99['Season'] = 1999
NB98['Season'] = 1998
NB97['Season'] = 1997
NB96['Season'] = 1996
NB95['Season'] = 1995

In [6]:
frames = [NB20, NB19, NB18, NB17, NB16, NB15, NB14, NB13, NB12, NB11, NB10, NB09, NB08, NB07, NB06, NB05, NB04, NB03, NB02, NB01, NB00, NB99, NB98, NB97, NB96, NB95]
data = pd.concat(frames, axis = 0)
data

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season
0,1,Steven Adams,C,26,OKC,58,58,1564,262,443,...,196,347,543,141,50,65,86,111,633,2020
1,2,Bam Adebayo,PF,22,MIA,65,65,2235,408,719,...,165,518,683,333,78,85,185,164,1053,2020
2,3,LaMarcus Aldridge,C,34,SAS,53,53,1754,391,793,...,103,289,392,129,36,87,74,128,1001,2020
3,4,Nickeil Alexander-Walker,SG,21,NOP,41,0,501,77,227,...,8,72,80,74,11,7,40,46,211,2020
4,5,Grayson Allen,SG,24,MEM,30,0,498,79,176,...,5,61,66,43,6,1,23,36,221,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,403,David Wood,PF,30,GSW,78,13,1336,153,326,...,83,158,241,65,28,13,53,217,428,1995
468,404,Randy Woods,PG,24,LAC,62,3,495,37,117,...,10,34,44,134,41,0,55,87,124,1995
469,405,Haywoode Workman,PG,29,IND,69,14,1028,101,269,...,21,90,111,194,59,5,73,115,292,1995
470,406,Sharone Wright,C,22,PHI,79,49,2044,361,776,...,191,281,472,48,37,104,151,246,904,1995
471,407,Danny Young,PG,32,MIL,7,0,77,9,17,...,1,4,5,12,4,0,4,8,24,1995

In [7]:
data.to_csv (r'NBAStats95to20Totals.csv', index = False, header=True)